# Generated by Django 5.0.7 on 2025-05-15 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core__c', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessage',
            name='message_id',
            field=models.CharField(default='', editable=False, max_length=100),
        ),
    ]
