# Generated by Django 5.0.7 on 2025-05-15 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core__c', '0002_chatmessage_message_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatmessage',
            name='message_id',
            field=models.CharField(default='38771737-7814-4da1-bd7b-0c0725fb95d6', editable=False, max_length=100, unique=True),
        ),
    ]
