# Generated by Django 5.0.7 on 2025-05-15 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core__c', '0004_alter_chatmessage_message_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatmessage',
            name='message_id',
            field=models.CharField(default='ef40ddb2-f16e-4a07-afea-39bba4639a8d', editable=False, max_length=100, unique=True),
        ),
    ]
