# Generated by Django 5.0.7 on 2025-05-16 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core__c', '0007_alter_chatmessage_message_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatmessage',
            name='message_id',
            field=models.CharField(default='da5409c2-fa87-4ad4-b6a3-b34240c6698d', editable=False, max_length=100, unique=True),
        ),
    ]
