# Generated by Django 5.0.7 on 2025-05-16 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core__c', '0008_alter_chatmessage_message_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatmessage',
            name='message_id',
            field=models.CharField(default='a94c2a5d-c99e-4ccb-8114-b1c5da7db1b0', editable=False, max_length=100, unique=True),
        ),
    ]
