# Generated by Django 5.0.7 on 2025-05-17 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core__c', '0009_alter_chatmessage_message_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatmessage',
            name='message_id',
            field=models.CharField(default='09b84be0-60ea-409a-ae0f-2c7fd17add07', editable=False, max_length=100, unique=True),
        ),
    ]
