# Generated by Django 5.0.7 on 2025-05-18 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core__c', '0010_alter_chatmessage_message_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatmessage',
            name='message_id',
            field=models.CharField(default='785afb6a-39c5-4b1c-b56e-71c2063effa4', editable=False, max_length=100, unique=True),
        ),
    ]
