# Generated by Django 5.0.7 on 2025-05-18 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core__c', '0011_alter_chatmessage_message_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatmessage',
            name='message_id',
            field=models.CharField(default='e08579a4-d3ec-4254-b006-245dcce4edb9', editable=False, max_length=100, unique=True),
        ),
    ]
