# Generated by Django 5.0.7 on 2025-05-18 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core__c', '0012_alter_chatmessage_message_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatmessage',
            name='message_id',
            field=models.CharField(default='4e4b90fa-d38a-4150-9a07-b87f842d5a37', editable=False, max_length=100, unique=True),
        ),
    ]
