# Generated by Django 5.0.7 on 2025-05-18 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core__c', '0013_alter_chatmessage_message_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatmessage',
            name='message_id',
            field=models.CharField(default='450645e0-e5a0-4ca3-9499-d6cc0d3bc24e', editable=False, max_length=100, unique=True),
        ),
    ]
