# Generated by Django 5.0.7 on 2025-05-18 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core__c', '0014_alter_chatmessage_message_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatmessage',
            name='message_id',
            field=models.CharField(default='4b87dc50-4dea-4e71-aff4-494e8716c50c', editable=False, max_length=100, unique=True),
        ),
    ]
