# Generated by Django 5.0.7 on 2025-05-18 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core__c', '0015_alter_chatmessage_message_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatmessage',
            name='message_id',
            field=models.CharField(default='196128b3-7130-4f89-9d82-a0e8717e0925', editable=False, max_length=100, unique=True),
        ),
    ]
