# Generated by Django 5.0.7 on 2025-05-20 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core__c', '0017_alter_chatmessage_message_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatmessage',
            name='message_id',
            field=models.CharField(default='b7166bc9-2d12-483e-8c19-850c0b4d87fe', editable=False, max_length=100, unique=True),
        ),
    ]
