# Generated by Django 5.0.7 on 2025-05-20 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core__c', '0018_alter_chatmessage_message_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatmessage',
            name='message_id',
            field=models.CharField(default='715c9921-85f7-4aea-8eff-936fda7c8808', editable=False, max_length=100, unique=True),
        ),
    ]
