# Generated by Django 5.0.7 on 2025-05-20 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core__c', '0019_alter_chatmessage_message_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatmessage',
            name='message_id',
            field=models.CharField(default='8a149799-2328-4eaf-8bd2-24d654958921', editable=False, max_length=100, unique=True),
        ),
    ]
