# Generated by Django 5.0.7 on 2025-05-20 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core__c', '0020_alter_chatmessage_message_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatmessage',
            name='message_id',
            field=models.CharField(default='5a696d82-a40b-4479-95e6-008948062b49', editable=False, max_length=100, unique=True),
        ),
    ]
