# Generated by Django 5.0.7 on 2025-05-20 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core__c', '0023_alter_chatmessage_message_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatmessage',
            name='message_id',
            field=models.CharField(default='628bcd3a-b8c8-4263-b6f8-0712aa0e5baa', editable=False, max_length=100, unique=True),
        ),
    ]
