# Generated by Django 5.0.7 on 2025-05-21 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core__c', '0024_alter_chatmessage_message_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatmessage',
            name='message_id',
            field=models.CharField(default='f4515dce-85a7-46bd-9d56-8f19993961b5', editable=False, max_length=100, unique=True),
        ),
    ]
