# Generated by Django 5.0.7 on 2025-05-22 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core__c', '0025_alter_chatmessage_message_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessage',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='chat_files/'),
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='is_read',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='chatmessage',
            name='message_id',
            field=models.CharField(default='b90c7f99-cc16-4f7e-9ce6-a4eaa8172ef5', editable=False, max_length=100, unique=True),
        ),
    ]
