# Generated by Django 5.0.7 on 2025-05-22 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core__c', '0026_chatmessage_file_chatmessage_is_read_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatmessage',
            name='message_id',
            field=models.CharField(default='b3720fa8-da85-444e-a86c-6f09d0f0a5cc', editable=False, max_length=100, unique=True),
        ),
    ]
