# Generated by Django 5.0.7 on 2025-05-02 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core__a', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='otp_delay',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
