# Generated by Django 5.0.7 on 2025-05-08 14:28

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core__a', '0003_contactticket'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('patient', 'patient'), ('doctor', 'doctor')], db_index=True, default='patient', max_length=50),
        ),
        migrations.AlterField(
            model_name='user',
            name='users_messaging_container',
            field=models.ManyToManyField(blank=True, related_name='messaging_container', to=settings.AUTH_USER_MODEL),
        ),
    ]
