# Generated by Django 5.0.7 on 2025-05-11 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core__a', '0006_cities'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cities',
            name='city_id',
            field=models.CharField(blank=True, db_index=True, default='', max_length=100, null=True, unique=True),
        ),
    ]
