# Generated by Django 5.0.7 on 2025-05-17 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core__a', '0007_alter_cities_city_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='account_type',
        ),
        migrations.RemoveField(
            model_name='user',
            name='credits',
        ),
        migrations.AddField(
            model_name='user',
            name='specialization',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True),
        ),
    ]
