# Generated by Django 5.0.7 on 2025-05-18 07:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core__a', '0009_doctortimeslots'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctortimeslots',
            name='doctor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slotes', to=settings.AUTH_USER_MODEL),
        ),
    ]
