# Generated by Django 5.0.7 on 2025-05-19 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core__a', '0010_alter_doctortimeslots_doctor'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctortimeslots',
            name='days',
            field=models.CharField(choices=[('Monday', 'Monday'), ('Tuesday', 'Tuesday'), ('Wednesday', 'Wednesday'), ('Thursday', 'Thursday'), ('Friday', 'Friday'), ('Saturday', 'Saturday'), ('Sunday', 'Sunday')], db_index=True, default='Monday', max_length=100),
        ),
        migrations.AlterField(
            model_name='doctortimeslots',
            name='date',
            field=models.DateField(blank=True, db_index=True, null=True),
        ),
    ]
