# Generated by Django 5.0.7 on 2025-05-20 06:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core__a', '0011_doctortimeslots_days_alter_doctortimeslots_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='doctortimeslots',
            options={'ordering': ['start_time'], 'verbose_name': 'Doctor Time Slot', 'verbose_name_plural': 'Doctor Time Slots'},
        ),
        migrations.AlterUniqueTogether(
            name='doctortimeslots',
            unique_together={('doctor', 'start_time')},
        ),
        migrations.RemoveField(
            model_name='doctortimeslots',
            name='date',
        ),
    ]
