# Generated by Django 5.0.7 on 2025-05-20 11:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core__a', '0012_alter_doctortimeslots_options_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='doctortimeslots',
            unique_together={('doctor', 'start_time', 'days', 'end_time')},
        ),
    ]
