# Generated by Django 5.0.7 on 2025-05-20 11:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core__a', '0013_alter_doctortimeslots_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='doctortimeslots',
            unique_together={('doctor', 'start_time', 'end_time')},
        ),
    ]
