# Generated by Django 5.0.7 on 2025-05-20 12:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core__a', '0014_alter_doctortimeslots_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='doctortimeslots',
            unique_together=set(),
        ),
    ]
