# Generated by Django 5.0.7 on 2025-05-16 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core__e', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='analysis',
            name='is_corrected',
            field=models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], default='NA', max_length=10),
        ),
    ]
