# Generated by Django 5.0.7 on 2025-05-09 07:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PatientXray',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('_id', models.CharField(db_index=True, default='', max_length=50)),
                ('image', models.ImageField(db_index=True, default=None, upload_to='patients/Xrays')),
                ('is_annovated', models.BooleanField(db_index=True, default=False)),
                ('user', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Patients',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('_id', models.CharField(db_index=True, default='', max_length=50)),
                ('first_name', models.CharField(db_index=True, default='', max_length=100)),
                ('last_name', models.CharField(db_index=True, default='', max_length=100)),
                ('date_of_birth', models.DateField(db_index=True, default=None)),
                ('patient_ssn', models.CharField(db_index=True, max_length=50, unique=True)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Not Confirmed', 'Not Confirmed')], db_index=True, default='', max_length=50)),
                ('doctor', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('patient_xrays', models.ManyToManyField(default='', to='core__p.patientxray')),
            ],
        ),
    ]
