# Generated by Django 5.0.7 on 2025-05-09 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core__p', '0003_patientxray_created_at_patientxray_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientxray',
            name='x_image',
            field=models.ImageField(blank=True, db_index=True, default=None, null=True, upload_to='patients/Xrays'),
        ),
    ]
