# Generated by Django 5.0.7 on 2025-05-15 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core__p', '0004_patientxray_x_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patients',
            name='patient_xrays',
            field=models.ManyToManyField(blank=True, default='', to='core__p.patientxray'),
        ),
    ]
