# Generated by Django 5.0.7 on 2025-05-18 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core__p', '0008_appointments_doctor_appointments_patient_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointments',
            name='status',
            field=models.CharField(choices=[('pending', 'pending'), ('approved', 'approved'), ('resolved', 'resolved')], db_index=True, default='NA', max_length=100),
        ),
    ]
