# Generated by Django 5.0.7 on 2025-05-20 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core__p', '0010_alter_appointments_status_appointmentfeedback'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointmentfeedback',
            name='is_feedback',
            field=models.BooleanField(default=False),
        ),
    ]
