# Generated by Django 5.0.7 on 2025-05-22 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core__p', '0011_appointmentfeedback_is_feedback'),
    ]

    operations = [
        migrations.AddField(
            model_name='patients',
            name='patient_email',
            field=models.EmailField(blank=True, db_index=True, default=None, max_length=254, null=True),
        ),
    ]
